// src/reporters/MarkdownReporter.ts
import * as fs from 'fs/promises';
import * as path from 'path';
import { AnalysisResults, ReportingConfig, Logger } from '../types';

export class MarkdownReporter {
  constructor(private config: ReportingConfig, private logger: Logger) {}

  public async generate(results: AnalysisResults): Promise<void> {
    const markdown = this.generateMarkdown(results);
    const filePath = path.join(this.config.outputDir, 'code-review-report.md');
    await fs.writeFile(filePath, markdown, 'utf-8');
  }

  private generateMarkdown(results: AnalysisResults): string {
    return `# Code Review & Security Audit Report

## Overall Score: ${results.overallScore}/100

**Target:** ${results.target.value}  
**Date:** ${results.timestamp}

## Component Scores

- 🔒 Security: ${results.scores.security}/100
- ⚡ Performance: ${results.scores.performance}/100
- 📝 Code Quality: ${results.scores.codeQuality}/100
- 🔍 SEO: ${results.scores.seo}/100
- ♿ Accessibility: ${results.scores.accessibility}/100

## Issues Summary

- **Critical:** ${results.summary.criticalIssues}
- **High:** ${results.summary.highIssues}
- **Medium:** ${results.summary.mediumIssues}
- **Low:** ${results.summary.lowIssues}

## Top Recommendations

${results.recommendations.slice(0, 5).map((r, i) => `${i + 1}. **${r.title}** (${r.priority})
   - ${r.description}`).join('\n\n')}

---
Generated by Code Review Agent v1.0.0
    `;
  }
}